title: Terence Chua # your name (or website title) here
logo: "/images/Terence_Linkedin_pic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  An aspiring AI scientist with experience in statistics, analytics, programming, disaster risk, geology, environmental science, gas price indices, and market trend. 
  <br><br>
  Fresh Graduate from NTU Asian School of the Environment.
  <br><br>
  Fluent in English and Mandarin; Skilled at communicating and presenting to audiences. Involved extensively into research work. Avid traveller and big fan of cultural exchanges. 
  <br><br>
  <a href="https://www.linkedin.com/in/terence-chua-7b7ba5157/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
